export const GET_RESULT_QUERY_SEARCH = "GET_RESULT_QUERY_SEARCH";
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const LOADING_QUERY_SEARCH = "LOADING_QUERY_SEARCH";
export const ERROR_QUERY_SEARCH = "ERROR_QUERY_SEARCH";
export const ERROR_DETAIL_PRODUCT  = "ERROR_DETAIL_PRODUCT ";
export const ERROR_PRODUCT  = "ERROR_PRODUCT ";